version: '2'
services:
  postgres:
    image: postgres:9.5
  redis:
    image: redis:3.2
  rails:
    build: .
    volumes:
      - .:/app
    entrypoint: bundle exec
  sidekiq:
    command: sidekiq
    extends:
      service: rails
    depends_on:
      - postgres
      - redis
  web:
    extends:
      service: rails
    command: rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
      - sidekiq
  guard:
    extends:
      service: rails
    command: guard -i
    depends_on:
      - postgres
      - redis
