version: '2'
services:
  postgres:
    image: postgres:9.5
  redis:
    image: redis:3.2
  rails:
    build: .
    volumes:
      - .:/app
  sidekiq:
    command: bundle exec sidekiq
    extends:
      service: rails
    depends_on:
      - postgres
      - redis
  web:
    extends:
      service: rails
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
      - sidekiq
