default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  host: db

development:
  <<: *default
  database: dprovider_development

test:
  <<: *default
  database: dprovider_test

production:
  <<: *default
  database: dprovider_production
  username: dprovider
  password: <%= ENV['DPROVIDER_DATABASE_PASSWORD'] %>
